# -*- coding: utf-8 -*-
"""1065 한수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1luTbCs9aM4ZmhykdU_WrBHSY8_QqeV0L
"""

N=int(input())

def sep(a):
  listA=[]
  while int(a)>0:
    k=a%10
    listA.append(k)
    a=a//10
  return listA

x=0
if N<100:
  print(N)
elif N<1000:
  for i in range(100,N+1):
    if sep(i)[0]-sep(i)[1]==sep(i)[1]-sep(i)[2]:
      x+=1
  print(x+99)
else:
  print(144)