# -*- coding: utf-8 -*-
"""11653 소인수분해.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q2ZIy7UlJ-R74RPifLy6gsWFEHeSQ4MF
"""

N=int(input())

k=[]
a=2
if N==1:
    print()
else:
  while N>1:
    if N%a==0:
      k.append(a)
      N/=a
    else:
      a+=1
      
for i in k:
  print(i)