# -*- coding: utf-8 -*-
"""1316 그룹 단어 체커.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ERfqxceFaZfGEzHBGytsfJtOaSJWKnC
"""

N=int(input())
words=[]
for _ in range(N):
  word=input()
  words.append(word)
  
l=[]
answer=0
for word in words:
  for i in list(word):
    l.append(word.index(i))
  if sorted(l)==l:
    answer+=1
  else:
    pass
  l=[]

print(answer)

word





