# -*- coding: utf-8 -*-
"""1978 소수찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q2ZIy7UlJ-R74RPifLy6gsWFEHeSQ4MF
"""

N=int(input())
listN=list(map(int,input().split()))

listN

k=[]
ns=0
for i in range(2,max(listN)+1):
  for j in range(N):
    if listN[j]%(i)==0:
      k.append(listN[j])
for i in k:
  if k.count(i)==1:
    ns+=1
print(ns)