# -*- coding: utf-8 -*-
"""2581 소수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q2ZIy7UlJ-R74RPifLy6gsWFEHeSQ4MF
"""

M=int(input())
N=int(input())

answer=[]
k=[]

if N==1:
  print(-1)
elif N==2:
  print(2)
  print(2)
else:  
  if M<=2:
    k.append(2)
  if M%2==1:
    for i in range(M,N+1,2):
      k.append(i)
    for i in range(M,N+1,2):
      for j in range(2,i):
        if i%j==0:
          try:
            k.remove(i)
          except:
            pass
  elif M%2==0:
    for i in range(M+1,N+1,2):
      k.append(i)
    for i in range(M+1,N+1,2):
      for j in range(2,i):
        if i%j==0:
          try:
            k.remove(i)
          except:
            pass
  try:
    k.remove(1)
  except:
    pass
  if len(k)!=0:
    print(sum(k))
    print(min(k))
  else:
    print(-1)