# -*- coding: utf-8 -*-
"""4673 셀프넘버.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1luTbCs9aM4ZmhykdU_WrBHSY8_QqeV0L
"""

def sep(a):
  listA=[]
  while int(a)>0:
    k=a%10
    listA.append(k)
    a=a//10
  return listA
 
l_min=[]

for j in range(1,10001):
  for i in range(j):
    l=i+sum(sep(i))
    if l==j:
      l_min.append(i)
  if len(l_min)==0:
    print(j,',',sep='')
  l_min=[]