# -*- coding: utf-8 -*-
"""6001_출력하기01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JysWeVCZSdgKxQ0opYWy49ie4wUaf6bW

python 언어에서 가장 기본적인 명령이 출력문이다.
print( )를 이용해 다음 단어를 출력하시오.

Hello
"""

print("Hello World")