# -*- coding: utf-8 -*-
"""6002_출력하기02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JysWeVCZSdgKxQ0opYWy49ie4wUaf6bW

이번에는 공백( )을 포함한 문장을 출력한다. 
다음 문장을 출력해보자.

Hello World
(대소문자에 주의한다.)
"""

print("Hello World")