# -*- coding: utf-8 -*-
"""6004_출력하기04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JysWeVCZSdgKxQ0opYWy49ie4wUaf6bW

이번에는 작은 따옴표(')(single quotation mark)가 들어있는 
출력문 연습을 해보자.

다음 문장을 출력하시오.

'Hello'

예시
print(" ' ");
"""

print("'Hello'")