# -*- coding: utf-8 -*-
"""6005_출력하기05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JysWeVCZSdgKxQ0opYWy49ie4wUaf6bW

이번에는 큰따옴표(")(double quotation mark)가 포함된 출력문을 연습해보자. 

다음 문장을 출력하시오.

"Hello World"
(단, 큰따옴표도 함께 출력한다.)

예시
print(' " ');
"""

print('"Hello World"')