# -*- coding: utf-8 -*-
"""6006_출력하기06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JysWeVCZSdgKxQ0opYWy49ie4wUaf6bW

이번에는 특수문자 출력에 도전하자!!

다음 문장을 출력하시오.

"!@#$%^&*()'
(단, 큰따옴표와 작은따옴표도 함께 출력한다.)
"""

print('"!@#$%^&*()\'')