# -*- coding: utf-8 -*-
"""6007_출력하기07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JysWeVCZSdgKxQ0opYWy49ie4wUaf6bW

윈도우 운영체제의 파일 경로를 출력하는 연습을 해보자.
 
파일 경로에는 특수문자들이 포함된다.

다음 경로를 출력하시오.

"C:\Download\'hello'.py"
(단, 따옴표도 함께 출력한다.)
"""

print('"C:\Download\\\'hello\'.py"')