# -*- coding: utf-8 -*-
"""10171_고양이

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JysWeVCZSdgKxQ0opYWy49ie4wUaf6bW

아래 예제와 같이 고양이를 출력하시오.
"""

print('\\    /\\')
print(" )  ( ')")
print("(  /  )")
print(" \(__)|")