# -*- coding: utf-8 -*-
"""2557_Hello World.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JysWeVCZSdgKxQ0opYWy49ie4wUaf6bW

Hello World!를 출력하시오.
"""

print('Hello World!')